### ISSUE TITLE
Change task class folder name

### ISSUE THREAD

**Issue by MrSlimCoder** [Mubasharaa/PapC1#1]

**Comment by Mubasharaa** [comment]
change a class task as task

**Comment by SabahatZainab** [comment]
change the name
![Capture](https://user-images.githubusercontent.com/64367762/192136260-d93bc264-bbe9-400c-ad05-1910fedf81d1.PNG)

**Comment by MrSlimCoder** [comment]
I will work on this issue please assign me.

**Comment by Mubasharaa** [comment]
> 

I will assign a issue soon

**Comment by SabahatZainab** [comment]
I will review this PR
